# -*- coding: utf-8 -*-
"""app.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Tj24FIjAOZrRcqw0eCS7nHNwmVAXWE-u
"""

# Import the libraries required for the Streamlit application.
# These libraries handle the interface, data processing, model and evaluation.
# !pip install -q streamlit


import streamlit as st
import pandas as pd
import numpy as np
import joblib

from sklearn.metrics import (
    accuracy_score,
    roc_auc_score,
    precision_score,
    recall_score,
    f1_score,
    matthews_corrcoef,
    confusion_matrix,
    classification_report
)


# Configure the Streamlit page title and layout.
st.set_page_config(
    page_title="Credit Default Prediction",
    page_icon="💳",
    layout="wide"
)


# Display the application title and a short description.
st.title("💳 Credit Card Default Prediction")
st.write(
    "Upload the test dataset and select a machine learning model "
    "to evaluate credit card default predictions."
)

# Define the available pre-trained model.
# The model files are stored inside the model folder.

model_paths = {
    "Logistic Regression": "model/logistic_regression.pkl",
    "Decision Tree": "model/decision_tree.pkl",
    "kNN": "model/knn.pkl",
    "Naive Bayes": "model/naive_bayes.pkl",
    "Random Forest": "model/random_forest.pkl"
}


# Allow the user to select one pre-trained model.
selected_model_name = st.selectbox(
    "Select a Machine Learning Model",
    list(model_paths.keys())
)

# Allow the user to upload the test CSV file.
# Only test data is uploaded to the application as required by the assignment.

uploaded_file = st.file_uploader(
    "Upload Test CSV File",
    type=["csv"]
)

# Process the uploaded test dataset.
# The uploaded file must contain the "default" target column.

if uploaded_file is not None:

    # Read the uploaded CSV file.
    test_data = pd.read_csv(uploaded_file)

    st.success("Test CSV uploaded successfully.")

    # Check whether the target column is available.
    if "default" not in test_data.columns:
        st.error("The uploaded CSV must contain the 'default' target column.")
        st.stop()

    # Separate input features and actual target values.
    X_test_app = test_data.drop(columns=["default"])
    y_test_app = test_data["default"]

    # Load the selected pre-trained model.
    model = joblib.load(model_paths[selected_model_name])

    # Generate predictions and probabilities.
    y_pred = model.predict(X_test_app)
    y_prob = model.predict_proba(X_test_app)[:, 1]

    st.success(f"{selected_model_name} loaded and predictions generated.")

    # Calculate the six required evaluation metrics.
    accuracy = accuracy_score(y_test_app, y_pred)
    auc = roc_auc_score(y_test_app, y_prob)
    precision = precision_score(y_test_app, y_pred, zero_division=0)
    recall = recall_score(y_test_app, y_pred, zero_division=0)
    f1 = f1_score(y_test_app, y_pred, zero_division=0)
    mcc = matthews_corrcoef(y_test_app, y_pred)

    # Display the model performance.
    st.subheader("Model Performance")

    col1, col2, col3 = st.columns(3)
    col4, col5, col6 = st.columns(3)

    col1.metric("Accuracy", f"{accuracy:.4f}")
    col2.metric("AUC", f"{auc:.4f}")
    col3.metric("Precision", f"{precision:.4f}")
    col4.metric("Recall", f"{recall:.4f}")
    col5.metric("F1 Score", f"{f1:.4f}")
    col6.metric("MCC", f"{mcc:.4f}")

    # Create and display the confusion matrix.
# It shows correct and incorrect predictions for both classes.

    st.subheader("Confusion Matrix")

    cm = confusion_matrix(y_test_app, y_pred)

    cm_df = pd.DataFrame(
        cm,
        index=["Actual 0", "Actual 1"],
        columns=["Predicted 0", "Predicted 1"]
    )

    st.dataframe(cm_df)

    # Generate and display the classification report.
# It provides precision, recall and F1-score for both target classes.

    st.subheader("Classification Report")

    report = classification_report(
        y_test_app,
        y_pred,
        target_names=["No Default (0)", "Default (1)"],
        output_dict=True,
        zero_division=0
    )

    report_df = pd.DataFrame(report).transpose()

    st.dataframe(report_df)

    # Create a prediction output file for the uploaded test data.
# The actual and predicted values are included for easy evaluation.

    prediction_output = X_test_app.copy()

    prediction_output["actual_default"] = y_test_app.values
    prediction_output["predicted_default"] = y_pred
    prediction_output["default_probability"] = y_prob

    csv_output = prediction_output.to_csv(index=False)

    st.subheader("Prediction Results")

    st.dataframe(prediction_output.head(10))

    # Provide the predictions as a downloadable CSV file.
    st.download_button(
        label="Download Predictions CSV",
        data=csv_output,
        file_name=f"{selected_model_name.lower().replace(' ', '_')}_predictions.csv",
        mime="text/csv"
    )